package com.velocitypackage.webj.materials.hypertext;


import java.util.Objects;

public class Attribute
{
    
    private final AttributeName a;
    private final String value;
    
    public Attribute(AttributeName a, String value)
    {
        this.a = a;
        this.value = value;
    }
    
    public AttributeName getIdentifier()
    {
        return a;
    }
    
    public String getValue()
    {
        return value;
    }
    
    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        Attribute attribute = (Attribute) o;
        return a == attribute.a && value.equals(attribute.value);
    }
    
    @Override
    public int hashCode()
    {
        return Objects.hash(a, value);
    }
    
    public enum AttributeName
    {
        ACCEPT, ACCEPT_CHARSET, ACCESSKEY, ACTION, ALIGN, ALT, ASYNC, AUTOCOMPLETE, AUTOFOCUS, AUTOPLAY, BGCOLOR, BORDER, CHARSET, CHECKED, CITE, CLASS, COLOR, COLS, COLSPAN, CONTENT, CONTENTEDITABLE, CONTROLS, COORDS, DATA, DATETIME, DEFAULT, DEFER, DIR, DIRNAME, DISABLED, DOWNLOAD, DRAGGABLE, ENCTYPE, FOR, FORM, FORMACTION, HEADERS, HEIGHT, HIDDEN, HIGH, HREF, HREFLANG, HTTP_EQUIV, ID, ISMAP, KIND, LABEL, LANG, LIST, LOOP, LOW, MAX, MAXLENGTH, MEDIA, METHOD, MIN, MULTIPLE, MUTED, NAME, NOVALIDATE, ONABORT, ONAFTERPRINT, ONBEFOREPRINT, ONBEFOREUNLOAD, ONBLUR, ONCANPLAY, ONCANPLAYTHROUGH, ONCHANGE, ONCLICK, ONCONTEXTMENU, ONCOPY, ONCUECHANGE, ONCUT, ONDBLCLICK, ONDRAG, ONDRAGEND, ONDRAGENTER, ONDRAGLEAVE, ONDRAGOVER, ONDRAGSTART, ONDROP, ONDURATIONCHANGE, ONEMPTIED, ONENDED, ONERROR, ONFOCUS, ONHASHCHANGE, ONINPUT, ONINVALID, ONKEYDOWN, ONKEYPRESS, ONKEYUP, ONLOAD, ONLOADEDDATA, ONLOADEDMETADATA, ONLOADSTART, ONMOUSEDOWN, ONMOUSEMOVE, ONMOUSEOUT, ONMOUSEOVER, ONMOUSEUP, ONMOUSEWHEEL, ONOFFLINE, ONONLINE, ONPAGEHIDE, ONPAGESHOW, ONPASTE, ONPAUSE, ONPLAY, ONPLAYING, ONPOPSTATE, ONPROGRESS, ONRATECHANGE, ONRESET, ONRESIZE, ONSCROLL, ONSEARCH, ONSEEKED, ONSEEKING, ONSELECT, ONSTALLED, ONSTORAGE, ONSUBMIT, ONSUSPEND, ONTIMEUPDATE, ONTOGGLE, ONUNLOAD, ONVOLUMECHANGE, ONWAITING, ONWHEEL, OPEN, OPTIMUM, PATTERN, PLACEHOLDER, POSTER, PRELOAD, READONLY, REL, REQUIRED, REVERSED, ROWS, ROWSPAN, SANDBOX, SCOPE, SELECTED, SHAPE, SIZE, SIZES, SPAN, SPELLCHECK, SRC, SRCDOC, SRCLANG, SRCSET, START, STEP, STYLE, TABINDEX, TARGET, TITLE, TRANSLATE, TYPE, USEMAP, VALUE, WIDTH, WRAP
    }
}


