name: Deploy

on:
  release:
    types: [ created ]

jobs:
  deploy:
    name: Deploy latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up VelocityPackage Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: archiva.internal
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Update version
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
      - name: Deploy
        run: mvn clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}